### ISSUE TITLE
Add support for custom configuration 

### ISSUE THREAD

**Issue by AlixANNERAUD** [bytecodealliance/wamr-rust-sdk#47]
WAMR offers a wide variety of configurations. However, currently, the `wamr_rust_sdk` does not provide a way to define these settings, which is unfortunate. To address this issue, I have thought of two solutions: either using Rust's feature system for binary settings and/or using environment variables (for text / number settings and/or binary settings). If this approach is acceptable to you, I can create a PR.

**Comment by lum1n0us** [comment]
Sounds good for me. Please go ahead.

**Comment by lum1n0us** [comment]
https://github.com/bytecodealliance/wamr-rust-sdk/pull/65

**Comment by lum1n0us** [comment]
Fixed by #65
