### ISSUE TITLE
Lifetime issues

### ISSUE THREAD

**Issue by AlixANNERAUD** [bytecodealliance/wamr-rust-sdk#75]
I think there's a lifetime issue with `Instance`, `Module` and `Runtime`, since `Instance` can outlive `Module`, and `Module` can outlive `Runtime` which leads to UB/segfault. A lifetime should be added to each object type and propagated to children "objects" (using using [PhatomData marker](https://doc.rust-lang.org/std/marker/struct.PhantomData.html#) since we are dealing with pointers). If you are ok with that, I can do the PR RN.

**Comment by lum1n0us** [comment]
> there's a lifetime issue with Instance, Module and Runtime, since Instance can outlive Module, and Module can outlive Runtime which leads to UB/segfault

I don't fully understand those points. Could you please provide us with more details or an example?

**Comment by AlixANNERAUD** [comment]
Lifetime in rust needs to be defined explicitly in rust when dealing with pointers / references.
The compiler always ensure that an explicit lifetime is defined for references in a struct but not for raw pointers.

**Comment by lum1n0us** [comment]
I get your point. That's a good one.

However, if we use the same logic, there's also a potential issue with the lifetime of `Instance` and `WASMModuleInstanceCommon`, as well as `Module` and `WASMModuleCommon`, `Function` and `WASMFuntionInstanceCommon` and so on.

The 'instance' field of `Instance` is a raw pointer to `WASMModuleInstanceCommon`, which also needs to indicate to the compiler that `Instance` has ownership of a `WASMModuleInstanceComm`

``` rust
// in src/instance.rs
pub struct Instance {
    instance: wasm_module_inst_t,
}
// in crates/wamr-sys/src/binding.rs
pub type wasm_module_inst_t = *mut WASMModuleInstanceCommon;
```
